name: presence_app
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

# TODO remove unnecessary dependencies
dependencies:
  flutter:
    sdk: flutter

  # utopia libs
  utopia_arch: ^0.5.0+8
  utopia_firebase_crashlytics: ^0.2.0
  utopia_hooks: ^0.4.10

  # architecture
  injector: ^3.0.0
  fast_immutable_collections: ^10.2.2

  # firebase
  firebase_core: ^2.4.1

  # platform APIs

  # misc widgets
  flutter_svg: ^2.0.0+1
  google_nav_bar: ^5.0.6
  date_picker_plus: ^4.1.0

  # misc utils
  intl: ^0.18.0
  search_highlight_text: ^1.0.0+2
  nfc_manager: ^3.5.0

  # web
  chaleno: ^0.0.7

  # code generator runtimes
  freezed_annotation: ^2.2.0
  json_annotation: ^4.3.0
  flutter_sheet_localization: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # code generators
  freezed: ^2.3.2
  json_serializable: ^6.0.1
  build_runner: ^2.1.5
  flutter_sheet_localization_generator:
    git:
      url: https://github.com/Utopia-USS/flutter_sheet_localization.git
      path: flutter_sheet_localization_generator
      ref: deps_update

  # lint
  utopia_lints: ^0.0.1+1

dependency_overrides:
  intl: ^0.18.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/uek_logo.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
